// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsFN7T7Ot0Zu3i2PPG5KE6M_wIMZMU5oo',
    appId: '1:232969473209:android:3557d4b8c9fb28831d5f68',
    messagingSenderId: '232969473209',
    projectId: 'nutesia',
    storageBucket: 'nutesia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdG8qgHjCGvj7Qz5Dvzu9ptWKVOhvMpzY',
    appId: '1:232969473209:ios:0fa3a5a18c97adba1d5f68',
    messagingSenderId: '232969473209',
    projectId: 'nutesia',
    storageBucket: 'nutesia.firebasestorage.app',
    iosBundleId: 'com.blueregan.nutesia',
  );
}
